### ISSUE TITLE
Make common commands easier

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter-docker-compose#3]
Let's think about if we could have the mixin make common commands easier to run, and with less yaml. Sometimes, for example with helm, this gave us an opportunity to add logic that adapted an imperative CLI to a more state driven experience to improve how the mixin worked over just using the CLI directly.

For example here is `up`command:

```yaml
docker-compose:
  description: "Run test services"
  arguments:
    - up
    - --detach
    - --no-color
```

Perhaps we could agree on a set of useful default when running docker-compose in a bundle, like you will usually want to run with --detach, and should not do color output because Porter doesn't support it. 

```yaml
docker-compose:
  description: "Run test services"
  command: up
```

## Questions
* Would this be helpful or get in the way?
* Would this be a maintenance problem?
* How would we tell people to tweak the defaults for a command? Override them with arguments and flags?
* What commands should get first class commands?
* Is this the right syntax for doing this? e.g.  `command: up` vs something like 

```yaml
up:
    - serviceA
    - serviceB
```

or

```yaml
up: serviceA serviceB...
```

**Comment by jaudiger** [comment]
Here are my thoughts. I think docker-compose mixin should at least support the most used docker-compose commands. I have in mind:
- up
- down
- pull

If someone wants another command, this could be done later. At least, these commands subset could fulfill a lot of use cases right now.

For each command, the docker-compose mixin could provide the following (but not complete) syntaxes:

1. up: As suggested by @carolynvs, the arguments `--detach` and `--no-color` should be provided by default, in addition of that:
```yml
docker-compose:
  description: "Run services"
  command: up
  services:
  - serviceA
  - serviceB
  recreate: false # Implies `--force-recreate`
  build: false # Implies `----build`
  remove-orphans: false # Implies `--remove-orphans`
``` 
2. down
```yml
docker-compose:
  description: "Shutdown services"
  command: down
  volumes: false # Implies `--volumes`
  remove-orphans: false # Implies `--remove-orphans`
``` 
3. pull
```yml
docker-compose:
  description: "Pull services"
  command: pull
  services:
  - serviceA
  - serviceB
```

**Comment by vdice** [comment]
The thoughts above look great to me!  One thing on the flags with comments -- they seem to be inverted?

Currently, for example:
```
remove-orphans: false # Implies `--remove-orphans`
```
I would assume if `remove-orphans` is set to `false`, the `--remove-orphans` flag would _not_ be appended to the docker-compose command, correct?  For this flag in particular, I would expect `false` to be the default value (maybe that's what was intended here?).  Then, if users want to override and set `remove-orphans` to `true`, the `--remove-orphans` flag _would_ be appended.

**Comment by jaudiger** [comment]
Exactly, this is was I was trying to say by using the `false` value. This value should be the default value and when the boolean is set to `true`, the variable implies the corresponding docker-compose argument.

I updated the example to reflect the comment, but it does not reflect the default value.

**Comment by jaudiger** [comment]
@vdice The discussion we are doing here (https://github.com/getporter/docker-mixin/issues/34) could be replicate dor docker-compose once we agree on the best approach.

**Comment by vdice** [comment]
@jaudiger Yes, as it sounds like https://github.com/getporter/docker-mixin/issues/34#issuecomment-885420690 is the preferred approach, we can certainly implement this similarly, with each supported command a first-class yaml field e.g.
```
docker-compose:
  description: "Pull services"
  pull:
    services:
    - serviceA
    - serviceB
```
